CONTAINER EnhancedOpenGLController
{
	NAME EnhancedOpenGLController;
	INCLUDE Texpression;
    
    GROUP ID_TAGPROPERTIES
	{
		LINK SMALL_FAR_AWAY_E_OPENGL_TRACK_OBJECT {}
		STATICTEXT SMALL_FAR_AWAY_E_OPENGL_DISTANCE_DISPLAY { ANIM OFF; }
		
		SEPARATOR { LINE; }
		
		STRING SMALL_FAR_AWAY_E_OPENGL_MESSAGES { ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; READONLY; }

		SEPARATOR { LINE; }

		REAL SMALL_FAR_AWAY_E_OPENGL_DISTANCE { UNIT METER; MIN 0.0; STEP 0.1; }
	}
}

