#ifndef _InstanceController_H_
#define _InstanceController_H_

enum
{
	SMALL_FAR_AWAY_INSTANCE_CONTROLLER_TRACK_OBJECT = 1001,
	SMALL_FAR_AWAY_INSTANCE_CONTROLLER_DISTANCE_DISPLAY = 1002,
	SMALL_FAR_AWAY_INSTANCE_CONTROLLER_DEFAULT_OBJECT = 1003,
	SMALL_FAR_AWAY_INSTANCE_CONTROLLER_MESSAGES = 1004,
	SMALL_FAR_AWAY_INSTANCE_CONTROLLER_ADD_BUTTON = 1005,
	
	SMALL_FAR_AWAY_INSTANCE_CONTROLLER_CONTAINER = 1101,
	
	SMALL_FAR_AWAY_INSTANCE_CONTROLLER_GROUP_OFFSET = 1500,
};

#endif

