CONTAINER LevelOfDetailController
{
	NAME LevelOfDetailController;
	INCLUDE Texpression;
    
    GROUP ID_TAGPROPERTIES
	{
		LINK SMALL_FAR_AWAY_LOD_TRACK_OBJECT {}
		STATICTEXT SMALL_FAR_AWAY_LOD_DISTANCE_DISPLAY { ANIM OFF; }
		STATICTEXT SMALL_FAR_AWAY_LOD { ANIM OFF; }
		
		SEPARATOR { LINE; }
		
		STRING SMALL_FAR_AWAY_LOD_MESSAGES { ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; READONLY; }
		
		SEPARATOR { LINE; }
		
		REAL SMALL_FAR_AWAY_LOD_MIN_DISTANCE { UNIT METER; MIN 0.0; STEP 0.1; }
		REAL SMALL_FAR_AWAY_LOD_MAX_DISTANCE { UNIT METER; MIN 0.0; STEP 0.1; }
		REAL SMALL_FAR_AWAY_LOD_MIN { MIN 0.0; MAX 100.0; STEP 1.0; UNIT PERCENT; }
		REAL SMALL_FAR_AWAY_LOD_MAX { MIN 0.0; MAX 100.0; STEP 1.0; UNIT PERCENT; }
	}
}


