#ifndef _LevelOfDetailController_H_
#define _LevelOfDetailController_H_

enum
{
	SMALL_FAR_AWAY_LOD_TRACK_OBJECT = 1001,
	SMALL_FAR_AWAY_LOD_DISTANCE_DISPLAY = 1002,
	SMALL_FAR_AWAY_LOD_MESSAGES = 1004,
	
	SMALL_FAR_AWAY_LOD_MIN_DISTANCE = 1107,
	SMALL_FAR_AWAY_LOD_MAX_DISTANCE = 1108,
	SMALL_FAR_AWAY_LOD_MIN = 1109,
	SMALL_FAR_AWAY_LOD_MAX = 1110,
	SMALL_FAR_AWAY_LOD = 1111,
};

#endif

