#ifndef _ObjectController_H_
#define _ObjectController_H_

enum
{
	SMALL_FAR_AWAY_OBJECT_CONTROLLER_TRACK_OBJECT = 1001,
	SMALL_FAR_AWAY_OBJECT_CONTROLLER_DISTANCE_DISPLAY = 1002,
	SMALL_FAR_AWAY_OBJECT_CONTROLLER_DEFAULT_OBJECT = 1003,
	SMALL_FAR_AWAY_OBJECT_CONTROLLER_MESSAGES = 1004,
	SMALL_FAR_AWAY_OBJECT_CONTROLLER_ADD_BUTTON = 1005,
	
	
	
	
	SMALL_FAR_AWAY_OBJECT_CONTROLLER_GROUP_OFFSET = 1500,
};

#endif

