CONTAINER PolygonReductionController
{
	NAME PolygonReductionController;
	INCLUDE Texpression;
    
    GROUP ID_TAGPROPERTIES
	{
		LINK SMALL_FAR_AWAY_POLYGON_REDUCTION_TRACK_OBJECT {}
		STATICTEXT SMALL_FAR_AWAY_POLYGON_REDUCTION_DISTANCE_DISPLAY { ANIM OFF; }
		STATICTEXT SMALL_FAR_AWAY_POLYGON_REDUCTION_REDUCTION_STRENGTH { ANIM OFF; }
		
		SEPARATOR { LINE; }
		
		STRING SMALL_FAR_AWAY_POLYGON_REDUCTION_MESSAGES { ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; READONLY; }
		
		SEPARATOR { LINE; }
		
		REAL SMALL_FAR_AWAY_POLYGON_REDUCTION_MIN_DISTANCE { UNIT METER; MIN 0.0; STEP 0.1; }
		REAL SMALL_FAR_AWAY_POLYGON_REDUCTION_MAX_DISTANCE { UNIT METER; MIN 0.0; STEP 0.1; }
		REAL SMALL_FAR_AWAY_POLYGON_REDUCTION_MIN_REDUCTION_STRENGTH { MIN 0.0; MAX 1.0; STEP 0.1; }
		REAL SMALL_FAR_AWAY_POLYGON_REDUCTION_MAX_REDUCTION_STRENGTH { MIN 0.0; MAX 1.0; STEP 0.1; }
	}
}


