#ifndef _PolygonReductionController_H_
#define _PolygonReductionController_H_

enum
{
	SMALL_FAR_AWAY_POLYGON_REDUCTION_TRACK_OBJECT = 1001,
	SMALL_FAR_AWAY_POLYGON_REDUCTION_DISTANCE_DISPLAY = 1002,
	SMALL_FAR_AWAY_POLYGON_REDUCTION_MESSAGES = 1004,
	
	SMALL_FAR_AWAY_POLYGON_REDUCTION_MIN_DISTANCE = 1107,
	SMALL_FAR_AWAY_POLYGON_REDUCTION_MAX_DISTANCE = 1108,
	SMALL_FAR_AWAY_POLYGON_REDUCTION_MIN_REDUCTION_STRENGTH = 1109,
	SMALL_FAR_AWAY_POLYGON_REDUCTION_MAX_REDUCTION_STRENGTH = 1110,
	SMALL_FAR_AWAY_POLYGON_REDUCTION_REDUCTION_STRENGTH = 1111,
};

#endif

