CONTAINER ShadingModeAndStyleController
{
	NAME ShadingModeAndStyleController;
	INCLUDE Texpression;
    
    GROUP ID_TAGPROPERTIES
	{
		LINK SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_TRACK_OBJECT {}
		STATICTEXT SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_DISTANCE_DISPLAY { ANIM OFF; }
		
		SEPARATOR { LINE; }
		
		STRING SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_MESSAGES { ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; READONLY; }
		
		SEPARATOR { LINE; }
		
		LONG SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_DEFAULT { 
            CYCLE 
            { 
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_GOURAUD_SHADING; 
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_GOURAUD_SHADING_LINES;
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_QUICK_SHADING;
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_QUICK_SHADING_LINES;
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_CONSTANT_SHADING;
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_CONSTANT_SHADING_LINES;
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_HIDDEN;
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_LINES;
            } 
		}
		
        LONG SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_WDISPLAYMODE_DEFAULT { 
            CYCLE 
            { 
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_WDISPLAYMODE_WIRE; 
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_WDISPLAYMODE_ISOPARM; 
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_WDISPLAYMODE_BOX; 
                SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_WDISPLAYMODE_SKELETON; 
            } 
        }
    
        SEPARATOR { LINE; }
        
		BUTTON SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_ADD_BUTTON { ANIM OFF; }
		
		SEPARATOR { LINE; }
	}
}
