#ifndef _ShadingModeAndStyleController_H_
#define _ShadingModeAndStyleController_H_

enum
{
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_TRACK_OBJECT = 1001,
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_DISTANCE_DISPLAY = 1002,
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_MESSAGES = 1004,
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_ADD_BUTTON = 1005,
	
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_DEFAULT = 1010,
    SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_WDISPLAYMODE_DEFAULT = 1011,
	
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_GOURAUD_SHADING = 0,
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_GOURAUD_SHADING_LINES = 1,
	
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_QUICK_SHADING = 2,
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_QUICK_SHADING_LINES = 3,
	
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_CONSTANT_SHADING = 7,
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_CONSTANT_SHADING_LINES = 4,
	
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_HIDDEN = 5,
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_SDISPLAYMODE_LINES = 6,
	
    SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_WDISPLAYMODE_WIRE = 0,
    SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_WDISPLAYMODE_ISOPARM = 1,
    SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_WDISPLAYMODE_BOX = 2,
    SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_WDISPLAYMODE_SKELETON = 3,
        
	SMALL_FAR_AWAY_SHADING_MODE_CONTROLLER_GROUP_OFFSET = 1500,
};

#endif

