#ifndef _TextureController_H_
#define _TextureController_H_

enum
{
	SMALL_FAR_AWAY_TEXTURE_TRACK_OBJECT = 1001,
	SMALL_FAR_AWAY_TEXTURE_DISTANCE_DISPLAY = 1002,
	SMALL_FAR_AWAY_TEXTURE_MESSAGES = 1004,
	
	SMALL_FAR_AWAY_TEXTURE_DISTANCE = 1107,
};

#endif

