CONTAINER VisibilityController
{
	NAME VisibilityController;
	INCLUDE Texpression;
    
    GROUP ID_TAGPROPERTIES
	{
		LINK SMALL_FAR_AWAY_VISIBILITY_TRACK_OBJECT {}
		STATICTEXT SMALL_FAR_AWAY_VISIBILITY_DISTANCE_DISPLAY { ANIM OFF; }
		
		SEPARATOR { LINE; }
		
		STRING SMALL_FAR_AWAY_VISIBILITY_MESSAGES { ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; READONLY; }

		SEPARATOR { LINE; }

		REAL SMALL_FAR_AWAY_VISIBILITY_DISTANCE { UNIT METER; MIN 0.0; STEP 0.1; }
		
		SEPARATOR { LINE; }
		
		BOOL SMALL_FAR_AWAY_VISIBILITY_VISIBILITY_EDITOR {}
		BOOL SMALL_FAR_AWAY_VISIBILITY_VISIBILITY_RENDER {}
		BOOL SMALL_FAR_AWAY_VISIBILITY_GENERATOR_FLAG {}
	}
}

