#ifndef _VisibilityController_H_
#define _VisibilityController_H_

enum
{
	SMALL_FAR_AWAY_VISIBILITY_TRACK_OBJECT = 1001,
	SMALL_FAR_AWAY_VISIBILITY_DISTANCE_DISPLAY = 1002,
	SMALL_FAR_AWAY_VISIBILITY_MESSAGES = 1004,
	
	SMALL_FAR_AWAY_VISIBILITY_DISTANCE = 1107,
	
	SMALL_FAR_AWAY_VISIBILITY_VISIBILITY_EDITOR = 1108,
	SMALL_FAR_AWAY_VISIBILITY_VISIBILITY_RENDER = 1109,
	SMALL_FAR_AWAY_VISIBILITY_GENERATOR_FLAG = 1110,

};

#endif

